#!/usr/bin/env bash
set -euo pipefail

# Generate a gdb init snippet that maps ROS 2 Debian build paths to local sources.
# This avoids hardcoding /usr/src/... versions inside launch.json.
#
# Output:
#   <repo_root>/.vscode/ros2_sources.gdbinit
#
# Usage:
#   ./ros2_ws/scripts/gen_gdb_source_map.sh [ros_distro]

ros_distro="${1:-jazzy}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out_dir="${repo_root}/.vscode"
out_file="${out_dir}/ros2_sources.gdbinit"

mkdir -p "${out_dir}"

# Compute exact Debian versions (these often appear in DWARF comp_dir as /usr/src/ros-<distro>-<pkg>-<Version>)
detect_deb_src_dir() {
  local pkg="$1"  # e.g. rclcpp, rcutils, rclcpp-action
  local ver=""
  if command -v dpkg-query >/dev/null 2>&1; then
    ver="$(dpkg-query -W -f='${Version}' "ros-${ros_distro}-${pkg}" 2>/dev/null || true)"
  fi

  if [[ -n "${ver}" ]]; then
    echo "/usr/src/ros-${ros_distro}-${pkg}-${ver}"
    return 0
  fi

  local guess=""
  guess="$(ls -d "/usr/src/ros-${ros_distro}-${pkg}-"* 2>/dev/null | head -n 1 || true)"
  if [[ -n "${guess}" ]]; then
    echo "${guess}"
    return 0
  fi

  echo ""
}

rclcpp_src_build="$(detect_deb_src_dir rclcpp)"
rcutils_src_build="$(detect_deb_src_dir rcutils)"
rclcpp_action_src_build="$(detect_deb_src_dir rclcpp-action)"
rclcpp_components_src_build="$(detect_deb_src_dir rclcpp-components)"
rclcpp_lifecycle_src_build="$(detect_deb_src_dir rclcpp-lifecycle)"

{
  echo "# Auto-generated by ros2_ws/scripts/gen_gdb_source_map.sh"
  echo "# Repo root: ${repo_root}"
  echo "set debuginfod enabled on"
  echo "set debuginfod urls https://debuginfod.ubuntu.com"
  echo "cd ${repo_root}"
  echo "directory ${repo_root}/third_party/glibc"

  # glibc build-relative mappings (useful when stepping into libc startup)
  echo "set substitute-path ./csu ${repo_root}/third_party/glibc/csu"
  echo "set substitute-path ./sysdeps ${repo_root}/third_party/glibc/sysdeps"
  echo "set substitute-path ./string/../sysdeps ${repo_root}/third_party/glibc/sysdeps"

  # libstdc++ common Ubuntu build path mappings (best-effort)
  echo "set substitute-path /build/gcc-14-ig5ci0/gcc-14-14.2.0/build/x86_64-linux-gnu/libstdc++-v3/include /usr/include/c++/13"
  echo "set substitute-path /build/gcc-14-ig5ci0/gcc-14-14.2.0/build/x86_64-linux-gnu/libstdc++-v3/include/x86_64-linux-gnu /usr/include/x86_64-linux-gnu/c++/13"

  if [[ -n "${rclcpp_src_build}" ]]; then
    # NOTE: rclcpp upstream repo is a super-repo containing multiple packages.
    # Debian's /usr/src/ros-<distro>-rclcpp-<ver> corresponds to the rclcpp package root.
    rclcpp_local_root="${repo_root}/third_party/rclcpp_repo"
    rclcpp_local_pkg="${rclcpp_local_root}/rclcpp"
    if [[ -d "${rclcpp_local_pkg}/src" ]]; then
      echo "set substitute-path ${rclcpp_src_build} ${rclcpp_local_pkg}"
    else
      echo "set substitute-path ${rclcpp_src_build} ${rclcpp_local_root}"
    fi
  else
    echo "# NOTE: rclcpp build path not detected; run dpkg-query or install ros-${ros_distro}-rclcpp"
  fi

  # Optional: map related packages if present. These are often stepped into when debugging actions/components.
  rclcpp_super_repo_root="${repo_root}/third_party/rclcpp_repo"
  if [[ -n "${rclcpp_action_src_build}" && -d "${rclcpp_super_repo_root}/rclcpp_action" ]]; then
    echo "set substitute-path ${rclcpp_action_src_build} ${rclcpp_super_repo_root}/rclcpp_action"
  fi
  if [[ -n "${rclcpp_components_src_build}" && -d "${rclcpp_super_repo_root}/rclcpp_components" ]]; then
    echo "set substitute-path ${rclcpp_components_src_build} ${rclcpp_super_repo_root}/rclcpp_components"
  fi
  if [[ -n "${rclcpp_lifecycle_src_build}" && -d "${rclcpp_super_repo_root}/rclcpp_lifecycle" ]]; then
    echo "set substitute-path ${rclcpp_lifecycle_src_build} ${rclcpp_super_repo_root}/rclcpp_lifecycle"
  fi

  if [[ -n "${rcutils_src_build}" ]]; then
    echo "set substitute-path ${rcutils_src_build} ${repo_root}/third_party/rcutils_repo"
  else
    echo "# NOTE: rcutils build path not detected; run dpkg-query or install ros-${ros_distro}-rcutils"
  fi
} >"${out_file}"

echo "[gen_gdb_source_map] Wrote: ${out_file}"
if [[ -n "${rclcpp_src_build}" ]]; then
  echo "[gen_gdb_source_map] rclcpp: ${rclcpp_src_build} -> ${repo_root}/third_party/rclcpp_repo/(rclcpp)"
fi
if [[ -n "${rcutils_src_build}" ]]; then
  echo "[gen_gdb_source_map] rcutils: ${rcutils_src_build} -> ${repo_root}/third_party/rcutils_repo"
fi
